# Generated by Django 5.1.1 on 2025-03-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PurchaseOrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('Stand', models.CharField(max_length=255)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('UnitPrice', models.FloatField()),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmodel.category')),
            ],
        ),
        migrations.CreateModel(
            name='MRF',
            fields=[
                ('mrf_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('quantity_requested', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmodel.department')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmodel.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('WarehouseLocation', models.CharField(max_length=255)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmodel.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('PurchaseOrderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('CostPrice', models.FloatField()),
                ('Subtotal', models.FloatField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmodel.product')),
                ('PurchaseOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmodel.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='SupplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmodel.supplier'),
        ),
    ]
